### ISSUE TITLE
Visual Studio and WinForms not cross compatible

### ISSUE THREAD

**Issue by IonicPixels** [microsoft/vs-editor-api#42]
Hello. I am a programmer who uses  C#/.NET with WinForms. I have heard of issues with WinForms being incompatible with MacOS and especially Linux. While at least one developer was able to get Linux working with WinForms, I don't think that program is compatible with MacOS. Even with "The Linux Update", people on Linux can't use Visual Studio itself to compile the most recent commits. It shouldn't matter the Distro of Linux being used, and both WinForms and Visual Studio should be natively cross compatible. Sure MacOS may be able to use Visual Studio but WinForms is still WIndows only. In a future update for Visual Studio, add Linux Compatibility, and if WinForms ever gets an update, that should also be cross compatible. Maybe the WinForms part shouldn't be in this Issue but I couldn't find a repository for it so I put it here.
-IonicPIxels

bottom text

**Comment by olegtk** [comment]
@IonicPixels, please report the issue as described in https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022, that is the best way to get help.

**Comment by IonicPixels** [comment]
> @IonicPixels, please report the issue as described in https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022, that is the best way to get help.

It isn't an issue I have all the time, just an issue when using Linux, and need to switch to Windows, and with the WinForms problem, I cant test my code on Linux
